site_name: DraftPro Docs
theme:
 name: material
 features:
  - navigation.tabs
  - navigation.sections
  - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
 language: en
 palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: blue grey
    accent: grey
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode 
    primary: blue grey
    accent: white

extra:
  social:
   - icon: fontawesome/brands/github-alt
     link: https://github.com/
   - icon: fontawesome/brands/x-twitter
     link: https://twitter.com/
  #  - icon: fontawesome/brands/Linkedin
  #    link: https://www.linkedin.com/in/
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      # emoji_index: !!python/name:materialx.emoji.twemoji
      # # emoji_generator: !!Python/name:materialx.emoji.to_svg

copyright: 
  Copyright &copy; 2024 <a href="https://github.com/" target="_blank" rel="noopener"> Rightal Tech </a>